openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/register:
    post:
      summary: ''
      operationId: postApiV1Register
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: dolor
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: chaz73@example.org
                password:
                  type: string
                  description: ''
                  example: voluptas
              required:
                - name
                - email
                - password
      security: []
  /api/v1/login:
    post:
      summary: ''
      operationId: postApiV1Login
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: repellendus
                password:
                  type: string
                  description: ''
                  example: non
              required:
                - email
                - password
      security: []
  /api/v1/movies:
    post:
      summary: ''
      operationId: postApiV1Movies
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: laboriosam
                summary:
                  type: string
                  description: ''
                  example: excepturi
                coverImage:
                  type: string
                  description: ''
                  example: repudiandae
                genreIds:
                  type: string
                  description: ''
                  example: repellat
                tagIds:
                  type: string
                  description: ''
                  example: eum
                imdbRatings:
                  type: string
                  description: ''
                  example: reprehenderit
                pdfLink:
                  type: string
                  description: ''
                  example: non
              required:
                - title
                - summary
                - coverImage
                - genreIds
                - tagIds
                - imdbRatings
                - pdfLink
      security: []
    put:
      summary: ''
      operationId: putApiV1Movies
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: magnam
                summary:
                  type: string
                  description: ''
                  example: eos
                coverImage:
                  type: string
                  description: ''
                  example: null
                genreIds:
                  type: string
                  description: ''
                  example: sit
                tagIds:
                  type: string
                  description: ''
                  example: voluptate
                imdbRatings:
                  type: string
                  description: ''
                  example: sit
                pdfLink:
                  type: string
                  description: ''
                  example: labore
              required:
                - title
                - summary
                - genreIds
                - tagIds
                - imdbRatings
                - pdfLink
      security: []
    delete:
      summary: ''
      operationId: deleteApiV1Movies
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    get:
      summary: ''
      operationId: getApiV1Movies
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  result:
                    data:
                      -
                        id: 5
                        title: 'Red Notice'
                        summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                        coverImage: 'http://localhost/images/movies/9PrFke5nH2..png'
                        imdbRatings: 6.9
                      -
                        id: 4
                        title: 'Red Notice'
                        summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                        coverImage: 'http://localhost/images/movies/KHZYMTP1k7..png'
                        imdbRatings: 6.9
                      -
                        id: 3
                        title: 'F 9'
                        summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                        coverImage: 'http://localhost/images/movies/xXpfHopPC9..png'
                        imdbRatings: 6.9
                      -
                        id: 1
                        title: 'Lorem Ipsum'
                        summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                        coverImage: 'http://localhost/images/movies/vBJGKV3uNk..png'
                        imdbRatings: 4.6
                    pagination:
                      lastPage: 1
                      currentPage: 1
                      perPage: 10
                      totalItems: 4
                  statusCode: 200
                  message: Success
                properties:
                  result:
                    type: object
                    properties:
                      data:
                        type: array
                        example:
                          -
                            id: 5
                            title: 'Red Notice'
                            summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage: 'http://localhost/images/movies/9PrFke5nH2..png'
                            imdbRatings: 6.9
                          -
                            id: 4
                            title: 'Red Notice'
                            summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage: 'http://localhost/images/movies/KHZYMTP1k7..png'
                            imdbRatings: 6.9
                          -
                            id: 3
                            title: 'F 9'
                            summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage: 'http://localhost/images/movies/xXpfHopPC9..png'
                            imdbRatings: 6.9
                          -
                            id: 1
                            title: 'Lorem Ipsum'
                            summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage: 'http://localhost/images/movies/vBJGKV3uNk..png'
                            imdbRatings: 4.6
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 5
                            title:
                              type: string
                              example: 'Red Notice'
                            summary:
                              type: string
                              example: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage:
                              type: string
                              example: 'http://localhost/images/movies/9PrFke5nH2..png'
                            imdbRatings:
                              type: number
                              example: 6.9
                      pagination:
                        type: object
                        properties:
                          lastPage:
                            type: integer
                            example: 1
                          currentPage:
                            type: integer
                            example: 1
                          perPage:
                            type: integer
                            example: 10
                          totalItems:
                            type: integer
                            example: 4
                  statusCode:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success
      tags:
        - Endpoints
      security: []
  '/api/v1/movies/{id}':
    get:
      summary: ''
      operationId: getApiV1MoviesId
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  result:
                    id: 1
                    title: 'Lorem Ipsum'
                    summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                    coverImage: 'http://localhost/images/movies/vBJGKV3uNk..png'
                    genres:
                      -
                        id: 1
                        name: Romance
                    authorName: thura
                    tags:
                      -
                        id: 1
                        name: Family
                    imdbRatings: 4.6
                    pdfLink: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'
                    relatedMovies:
                      -
                        id: 3
                        title: 'F 9'
                        summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                        coverImage: 'http://localhost/images/movies/xXpfHopPC9..png'
                        imdbRatings: 6.9
                      -
                        id: 4
                        title: 'Red Notice'
                        summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                        coverImage: 'http://localhost/images/movies/KHZYMTP1k7..png'
                        imdbRatings: 6.9
                      -
                        id: 5
                        title: 'Red Notice'
                        summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                        coverImage: 'http://localhost/images/movies/9PrFke5nH2..png'
                        imdbRatings: 6.9
                  statusCode: 200
                  message: Success
                properties:
                  result:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      title:
                        type: string
                        example: 'Lorem Ipsum'
                      summary:
                        type: string
                        example: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                      coverImage:
                        type: string
                        example: 'http://localhost/images/movies/vBJGKV3uNk..png'
                      genres:
                        type: array
                        example:
                          -
                            id: 1
                            name: Romance
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: Romance
                      authorName:
                        type: string
                        example: thura
                      tags:
                        type: array
                        example:
                          -
                            id: 1
                            name: Family
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: Family
                      imdbRatings:
                        type: number
                        example: 4.6
                      pdfLink:
                        type: string
                        example: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'
                      relatedMovies:
                        type: array
                        example:
                          -
                            id: 3
                            title: 'F 9'
                            summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage: 'http://localhost/images/movies/xXpfHopPC9..png'
                            imdbRatings: 6.9
                          -
                            id: 4
                            title: 'Red Notice'
                            summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage: 'http://localhost/images/movies/KHZYMTP1k7..png'
                            imdbRatings: 6.9
                          -
                            id: 5
                            title: 'Red Notice'
                            summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage: 'http://localhost/images/movies/9PrFke5nH2..png'
                            imdbRatings: 6.9
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 3
                            title:
                              type: string
                              example: 'F 9'
                            summary:
                              type: string
                              example: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage:
                              type: string
                              example: 'http://localhost/images/movies/xXpfHopPC9..png'
                            imdbRatings:
                              type: number
                              example: 6.9
                  statusCode:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the movie.'
        example: 1
        required: true
        schema:
          type: integer
  /api/v1/comment:
    post:
      summary: ''
      operationId: postApiV1Comment
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movieId:
                  type: integer
                  description: ''
                  example: 10
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: lucie40@example.com
                description:
                  type: string
                  description: ''
                  example: nostrum
              required:
                - movieId
                - email
                - description
      security: []
tags:
  -
    name: Endpoints
    description: ''
