openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/register:
    post:
      summary: ''
      operationId: postApiV1Register
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: natus
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: missouri.koch@example.net
                password:
                  type: string
                  description: ''
                  example: necessitatibus
              required:
                - name
                - email
                - password
      security: []
  /api/v1/login:
    post:
      summary: ''
      operationId: postApiV1Login
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: accusamus
                password:
                  type: string
                  description: ''
                  example: saepe
              required:
                - email
                - password
      security: []
  /api/v1/user-movies:
    get:
      summary: ''
      operationId: getApiV1UserMovies
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Token expired!'
                  data: null
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Token expired!'
                  data:
                    type: string
                    example: null
      tags:
        - Endpoints
      security: []
  /api/v1/movies:
    post:
      summary: ''
      operationId: postApiV1Movies
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: perspiciatis
                summary:
                  type: string
                  description: ''
                  example: cupiditate
                coverImage:
                  type: string
                  description: ''
                  example: et
                genreIds:
                  type: string
                  description: ''
                  example: quae
                tagIds:
                  type: string
                  description: ''
                  example: eaque
                imdbRatings:
                  type: string
                  description: ''
                  example: fuga
                pdfLink:
                  type: string
                  description: ''
                  example: sit
              required:
                - title
                - summary
                - coverImage
                - genreIds
                - tagIds
                - imdbRatings
                - pdfLink
      security: []
    put:
      summary: ''
      operationId: putApiV1Movies
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: repellendus
                summary:
                  type: string
                  description: ''
                  example: iure
                coverImage:
                  type: string
                  description: ''
                  example: null
                genreIds:
                  type: string
                  description: ''
                  example: voluptatibus
                tagIds:
                  type: string
                  description: ''
                  example: delectus
                imdbRatings:
                  type: string
                  description: ''
                  example: velit
                pdfLink:
                  type: string
                  description: ''
                  example: eos
              required:
                - title
                - summary
                - genreIds
                - tagIds
                - imdbRatings
                - pdfLink
      security: []
    delete:
      summary: ''
      operationId: deleteApiV1Movies
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    get:
      summary: ''
      operationId: getApiV1Movies
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  result:
                    data:
                      -
                        id: 2
                        title: 'Red Notice'
                        summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                        coverImage: 'http://localhost/images/movies/sCsyxNN434..png'
                        imdbRatings: 6.9
                        comments: null
                      -
                        id: 1
                        title: 'Red Notice'
                        summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                        coverImage: 'http://localhost/images/movies/xJ4c8H5bTU..png'
                        imdbRatings: 6.9
                        comments: null
                    pagination:
                      lastPage: 1
                      currentPage: 1
                      perPage: 10
                      totalItems: 2
                  statusCode: 200
                  message: Success
                properties:
                  result:
                    type: object
                    properties:
                      data:
                        type: array
                        example:
                          -
                            id: 2
                            title: 'Red Notice'
                            summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage: 'http://localhost/images/movies/sCsyxNN434..png'
                            imdbRatings: 6.9
                            comments: null
                          -
                            id: 1
                            title: 'Red Notice'
                            summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage: 'http://localhost/images/movies/xJ4c8H5bTU..png'
                            imdbRatings: 6.9
                            comments: null
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 2
                            title:
                              type: string
                              example: 'Red Notice'
                            summary:
                              type: string
                              example: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage:
                              type: string
                              example: 'http://localhost/images/movies/sCsyxNN434..png'
                            imdbRatings:
                              type: number
                              example: 6.9
                            comments:
                              type: string
                              example: null
                      pagination:
                        type: object
                        properties:
                          lastPage:
                            type: integer
                            example: 1
                          currentPage:
                            type: integer
                            example: 1
                          perPage:
                            type: integer
                            example: 10
                          totalItems:
                            type: integer
                            example: 2
                  statusCode:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success
      tags:
        - Endpoints
      security: []
  '/api/v1/movies/{id}':
    get:
      summary: ''
      operationId: getApiV1MoviesId
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  result:
                    id: 1
                    title: 'Red Notice'
                    summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                    coverImage: 'http://localhost/images/movies/xJ4c8H5bTU..png'
                    genres:
                      -
                        id: 1
                        name: Romance
                      -
                        id: 2
                        name: Comedy
                      -
                        id: 3
                        name: Horror
                    authorName: thura
                    tags:
                      -
                        id: 1
                        name: Family
                      -
                        id: 2
                        name: Dramatic
                      -
                        id: 3
                        name: Mysterious
                    imdbRatings: 6.9
                    pdfLink: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'
                    comments: null
                    relatedMovies:
                      -
                        id: 2
                        title: 'Red Notice'
                        summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                        coverImage: 'http://localhost/images/movies/sCsyxNN434..png'
                        imdbRatings: 6.9
                        comments: null
                  statusCode: 200
                  message: Success
                properties:
                  result:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      title:
                        type: string
                        example: 'Red Notice'
                      summary:
                        type: string
                        example: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                      coverImage:
                        type: string
                        example: 'http://localhost/images/movies/xJ4c8H5bTU..png'
                      genres:
                        type: array
                        example:
                          -
                            id: 1
                            name: Romance
                          -
                            id: 2
                            name: Comedy
                          -
                            id: 3
                            name: Horror
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: Romance
                      authorName:
                        type: string
                        example: thura
                      tags:
                        type: array
                        example:
                          -
                            id: 1
                            name: Family
                          -
                            id: 2
                            name: Dramatic
                          -
                            id: 3
                            name: Mysterious
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: Family
                      imdbRatings:
                        type: number
                        example: 6.9
                      pdfLink:
                        type: string
                        example: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'
                      comments:
                        type: string
                        example: null
                      relatedMovies:
                        type: array
                        example:
                          -
                            id: 2
                            title: 'Red Notice'
                            summary: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage: 'http://localhost/images/movies/sCsyxNN434..png'
                            imdbRatings: 6.9
                            comments: null
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 2
                            title:
                              type: string
                              example: 'Red Notice'
                            summary:
                              type: string
                              example: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
                            coverImage:
                              type: string
                              example: 'http://localhost/images/movies/sCsyxNN434..png'
                            imdbRatings:
                              type: number
                              example: 6.9
                            comments:
                              type: string
                              example: null
                  statusCode:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the movie.'
        example: 1
        required: true
        schema:
          type: integer
  /api/v1/comment:
    post:
      summary: ''
      operationId: postApiV1Comment
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movieId:
                  type: integer
                  description: ''
                  example: 7
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: hane.virgil@example.org
                description:
                  type: string
                  description: ''
                  example: libero
              required:
                - movieId
                - email
                - description
      security: []
tags:
  -
    name: Endpoints
    description: ''
